// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source: android.text.TextWatcher
// Copy this file to: runtime/java/com/stratum/adapters/
package com.stratum.adapters;

import android.util.Log;
import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_text_TextWatcher implements android.text.TextWatcher {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_text_TextWatcher(String key) {
        this.key_ = key;
        //Log.d(TAG, "[Adapter_android_text_TextWatcher] created key=" + key);
    }

    @Override
    public void beforeTextChanged(CharSequence arg0, int arg1, int arg2, int arg3) {
        //Log.d(TAG, "[Adapter_android_text_TextWatcher] beforeTextChanged key=" + key_ + " params=4");
        StratumInvocationHandler.nativeDispatch(
            key_, "beforeTextChanged", new Object[]{ arg0, Integer.valueOf(arg1), Integer.valueOf(arg2), Integer.valueOf(arg3) });
    }

    @Override
    public void onTextChanged(CharSequence arg0, int arg1, int arg2, int arg3) {
        //Log.d(TAG, "[Adapter_android_text_TextWatcher] onTextChanged key=" + key_ + " params=4");
        StratumInvocationHandler.nativeDispatch(
            key_, "onTextChanged", new Object[]{ arg0, Integer.valueOf(arg1), Integer.valueOf(arg2), Integer.valueOf(arg3) });
    }

    @Override
    public void afterTextChanged(android.text.Editable arg0) {
        //Log.d(TAG, "[Adapter_android_text_TextWatcher] afterTextChanged key=" + key_ + " params=1");
        StratumInvocationHandler.nativeDispatch(
            key_, "afterTextChanged", new Object[]{ arg0 });
    }

    @Override
    public String toString() {
        return "Adapter_android_text_TextWatcher[key=" + key_ + "]";
    }

}
