// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source: android.view.SurfaceHolder$Callback
// Copy this file to: runtime/java/com/stratum/adapters/
package com.stratum.adapters;

import android.util.Log;
import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_view_SurfaceHolder_Callback implements android.view.SurfaceHolder.Callback {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_view_SurfaceHolder_Callback(String key) {
        this.key_ = key;
        //Log.d(TAG, "[Adapter_android_view_SurfaceHolder_Callback] created key=" + key);
    }

    @Override
    public void surfaceCreated(android.view.SurfaceHolder arg0) {
        //Log.d(TAG, "[Adapter_android_view_SurfaceHolder_Callback] surfaceCreated key=" + key_ + " params=1");
        StratumInvocationHandler.nativeDispatch(
            key_, "surfaceCreated", new Object[]{ arg0 });
    }

    @Override
    public void surfaceChanged(android.view.SurfaceHolder arg0, int arg1, int arg2, int arg3) {
        //Log.d(TAG, "[Adapter_android_view_SurfaceHolder_Callback] surfaceChanged key=" + key_ + " params=4");
        StratumInvocationHandler.nativeDispatch(
            key_, "surfaceChanged", new Object[]{ arg0, Integer.valueOf(arg1), Integer.valueOf(arg2), Integer.valueOf(arg3) });
    }

    @Override
    public void surfaceDestroyed(android.view.SurfaceHolder arg0) {
        //Log.d(TAG, "[Adapter_android_view_SurfaceHolder_Callback] surfaceDestroyed key=" + key_ + " params=1");
        StratumInvocationHandler.nativeDispatch(
            key_, "surfaceDestroyed", new Object[]{ arg0 });
    }

    @Override
    public String toString() {
        return "Adapter_android_view_SurfaceHolder_Callback[key=" + key_ + "]";
    }

}
