// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source: android.webkit.ValueCallback
// Copy this file to: runtime/java/com/stratum/adapters/
package com.stratum.adapters;

import android.util.Log;
import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_webkit_ValueCallback implements android.webkit.ValueCallback {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_webkit_ValueCallback(String key) {
        this.key_ = key;
        //Log.d(TAG, "[Adapter_android_webkit_ValueCallback] created key=" + key);
    }

    @Override
    public void onReceiveValue(Object arg0) {
        //Log.d(TAG, "[Adapter_android_webkit_ValueCallback] onReceiveValue key=" + key_ + " params=1");
        StratumInvocationHandler.nativeDispatch(
            key_, "onReceiveValue", new Object[]{ arg0 });
    }

    @Override
    public String toString() {
        return "Adapter_android_webkit_ValueCallback[key=" + key_ + "]";
    }

}
