// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source: android.content.DialogInterface$OnDismissListener
// Copy this file to: runtime/java/com/stratum/adapters/
package com.stratum.adapters;

import android.util.Log;
import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_content_DialogInterface_OnDismissListener implements android.content.DialogInterface.OnDismissListener {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_content_DialogInterface_OnDismissListener(String key) {
        this.key_ = key;
        //Log.d(TAG, "[Adapter_android_content_DialogInterface_OnDismissListener] created key=" + key);
    }

    @Override
    public void onDismiss(android.content.DialogInterface arg0) {
        //Log.d(TAG, "[Adapter_android_content_DialogInterface_OnDismissListener] onDismiss key=" + key_ + " params=1");
        StratumInvocationHandler.nativeDispatch(
            key_, "onDismiss", new Object[]{ arg0 });
    }

    @Override
    public String toString() {
        return "Adapter_android_content_DialogInterface_OnDismissListener[key=" + key_ + "]";
    }

}
