// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source: android.media.MediaPlayer$OnErrorListener
// Copy this file to: runtime/java/com/stratum/adapters/
package com.stratum.adapters;

import android.util.Log;
import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_media_MediaPlayer_OnErrorListener implements android.media.MediaPlayer.OnErrorListener {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_media_MediaPlayer_OnErrorListener(String key) {
        this.key_ = key;
        //Log.d(TAG, "[Adapter_android_media_MediaPlayer_OnErrorListener] created key=" + key);
    }

    @Override
    public boolean onError(android.media.MediaPlayer arg0, int arg1, int arg2) {
        //Log.d(TAG, "[Adapter_android_media_MediaPlayer_OnErrorListener] onError key=" + key_ + " params=3");
        StratumInvocationHandler.nativeDispatch(
            key_, "onError", new Object[]{ arg0, Integer.valueOf(arg1), Integer.valueOf(arg2) });
        return false;
    }

    @Override
    public String toString() {
        return "Adapter_android_media_MediaPlayer_OnErrorListener[key=" + key_ + "]";
    }

}
