// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source: android.content.DialogInterface$OnClickListener
// Copy this file to: runtime/java/com/stratum/adapters/
package com.stratum.adapters;

import android.util.Log;
import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_content_DialogInterface_OnClickListener implements android.content.DialogInterface.OnClickListener {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_content_DialogInterface_OnClickListener(String key) {
        this.key_ = key;
        //Log.d(TAG, "[Adapter_android_content_DialogInterface_OnClickListener] created key=" + key);
    }

    @Override
    public void onClick(android.content.DialogInterface arg0, int arg1) {
        //Log.d(TAG, "[Adapter_android_content_DialogInterface_OnClickListener] onClick key=" + key_ + " params=2");
        StratumInvocationHandler.nativeDispatch(
            key_, "onClick", new Object[]{ arg0, Integer.valueOf(arg1) });
    }

    @Override
    public String toString() {
        return "Adapter_android_content_DialogInterface_OnClickListener[key=" + key_ + "]";
    }

}
