// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source: android.media.MediaPlayer$OnCompletionListener
// Copy this file to: runtime/java/com/stratum/adapters/
package com.stratum.adapters;

import android.util.Log;
import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_media_MediaPlayer_OnCompletionListener implements android.media.MediaPlayer.OnCompletionListener {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_media_MediaPlayer_OnCompletionListener(String key) {
        this.key_ = key;
        //Log.d(TAG, "[Adapter_android_media_MediaPlayer_OnCompletionListener] created key=" + key);
    }

    @Override
    public void onCompletion(android.media.MediaPlayer arg0) {
        //Log.d(TAG, "[Adapter_android_media_MediaPlayer_OnCompletionListener] onCompletion key=" + key_ + " params=1");
        StratumInvocationHandler.nativeDispatch(
            key_, "onCompletion", new Object[]{ arg0 });
    }

    @Override
    public String toString() {
        return "Adapter_android_media_MediaPlayer_OnCompletionListener[key=" + key_ + "]";
    }

}
