// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source: android.media.ImageReader$OnImageAvailableListener
// Copy this file to: runtime/java/com/stratum/adapters/
package com.stratum.adapters;

import android.util.Log;
import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_media_ImageReader_OnImageAvailableListener implements android.media.ImageReader.OnImageAvailableListener {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_media_ImageReader_OnImageAvailableListener(String key) {
        this.key_ = key;
        //Log.d(TAG, "[Adapter_android_media_ImageReader_OnImageAvailableListener] created key=" + key);
    }

    @Override
    public void onImageAvailable(android.media.ImageReader arg0) {
        //Log.d(TAG, "[Adapter_android_media_ImageReader_OnImageAvailableListener] onImageAvailable key=" + key_ + " params=1");
        StratumInvocationHandler.nativeDispatch(
            key_, "onImageAvailable", new Object[]{ arg0 });
    }

    @Override
    public String toString() {
        return "Adapter_android_media_ImageReader_OnImageAvailableListener[key=" + key_ + "]";
    }

}
