// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source: android.location.LocationListener
// Copy this file to: runtime/java/com/stratum/adapters/
package com.stratum.adapters;

import android.util.Log;
import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_location_LocationListener implements android.location.LocationListener {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_location_LocationListener(String key) {
        this.key_ = key;
        //Log.d(TAG, "[Adapter_android_location_LocationListener] created key=" + key);
    }

    @Override
    public void onLocationChanged(android.location.Location arg0) {
        //Log.d(TAG, "[Adapter_android_location_LocationListener] onLocationChanged key=" + key_ + " params=1");
        StratumInvocationHandler.nativeDispatch(
            key_, "onLocationChanged", new Object[]{ arg0 });
    }

    @Override
    public void onLocationChanged(java.util.List arg0) {
        //Log.d(TAG, "[Adapter_android_location_LocationListener] onLocationChanged key=" + key_ + " params=1");
        StratumInvocationHandler.nativeDispatch(
            key_, "onLocationChanged", new Object[]{ arg0 });
    }

    @Override
    public void onFlushComplete(int arg0) {
        //Log.d(TAG, "[Adapter_android_location_LocationListener] onFlushComplete key=" + key_ + " params=1");
        StratumInvocationHandler.nativeDispatch(
            key_, "onFlushComplete", new Object[]{ Integer.valueOf(arg0) });
    }

    @Override
    public void onStatusChanged(String arg0, int arg1, android.os.Bundle arg2) {
        //Log.d(TAG, "[Adapter_android_location_LocationListener] onStatusChanged key=" + key_ + " params=3");
        StratumInvocationHandler.nativeDispatch(
            key_, "onStatusChanged", new Object[]{ arg0, Integer.valueOf(arg1), arg2 });
    }

    @Override
    public void onProviderEnabled(String arg0) {
        //Log.d(TAG, "[Adapter_android_location_LocationListener] onProviderEnabled key=" + key_ + " params=1");
        StratumInvocationHandler.nativeDispatch(
            key_, "onProviderEnabled", new Object[]{ arg0 });
    }

    @Override
    public void onProviderDisabled(String arg0) {
        //Log.d(TAG, "[Adapter_android_location_LocationListener] onProviderDisabled key=" + key_ + " params=1");
        StratumInvocationHandler.nativeDispatch(
            key_, "onProviderDisabled", new Object[]{ arg0 });
    }

    @Override
    public String toString() {
        return "Adapter_android_location_LocationListener[key=" + key_ + "]";
    }

}
