// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source: android.widget.SeekBar$OnSeekBarChangeListener
// Copy this file to: runtime/java/com/stratum/adapters/
package com.stratum.adapters;

import android.util.Log;
import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_widget_SeekBar_OnSeekBarChangeListener implements android.widget.SeekBar.OnSeekBarChangeListener {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_widget_SeekBar_OnSeekBarChangeListener(String key) {
        this.key_ = key;
        //Log.d(TAG, "[Adapter_android_widget_SeekBar_OnSeekBarChangeListener] created key=" + key);
    }

    @Override
    public void onProgressChanged(android.widget.SeekBar arg0, int arg1, boolean arg2) {
        //Log.d(TAG, "[Adapter_android_widget_SeekBar_OnSeekBarChangeListener] onProgressChanged key=" + key_ + " params=3");
        StratumInvocationHandler.nativeDispatch(
            key_, "onProgressChanged", new Object[]{ arg0, Integer.valueOf(arg1), Boolean.valueOf(arg2) });
    }

    @Override
    public void onStartTrackingTouch(android.widget.SeekBar arg0) {
        //Log.d(TAG, "[Adapter_android_widget_SeekBar_OnSeekBarChangeListener] onStartTrackingTouch key=" + key_ + " params=1");
        StratumInvocationHandler.nativeDispatch(
            key_, "onStartTrackingTouch", new Object[]{ arg0 });
    }

    @Override
    public void onStopTrackingTouch(android.widget.SeekBar arg0) {
        //Log.d(TAG, "[Adapter_android_widget_SeekBar_OnSeekBarChangeListener] onStopTrackingTouch key=" + key_ + " params=1");
        StratumInvocationHandler.nativeDispatch(
            key_, "onStopTrackingTouch", new Object[]{ arg0 });
    }

    @Override
    public String toString() {
        return "Adapter_android_widget_SeekBar_OnSeekBarChangeListener[key=" + key_ + "]";
    }

}
