// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source: android.view.View$OnLongClickListener
// Copy this file to: runtime/java/com/stratum/adapters/
package com.stratum.adapters;

import android.util.Log;
import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_view_View_OnLongClickListener implements android.view.View.OnLongClickListener {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_view_View_OnLongClickListener(String key) {
        this.key_ = key;
        //Log.d(TAG, "[Adapter_android_view_View_OnLongClickListener] created key=" + key);
    }

    @Override
    public boolean onLongClick(android.view.View arg0) {
        //Log.d(TAG, "[Adapter_android_view_View_OnLongClickListener] onLongClick key=" + key_ + " params=1");
        StratumInvocationHandler.nativeDispatch(
            key_, "onLongClick", new Object[]{ arg0 });
        return false;
    }

    @Override
    public boolean onLongClickUseDefaultHapticFeedback(android.view.View arg0) {
        //Log.d(TAG, "[Adapter_android_view_View_OnLongClickListener] onLongClickUseDefaultHapticFeedback key=" + key_ + " params=1");
        StratumInvocationHandler.nativeDispatch(
            key_, "onLongClickUseDefaultHapticFeedback", new Object[]{ arg0 });
        return false;
    }

    @Override
    public String toString() {
        return "Adapter_android_view_View_OnLongClickListener[key=" + key_ + "]";
    }

}
