// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source: android.media.MediaPlayer$OnBufferingUpdateListener
// Copy this file to: runtime/java/com/stratum/adapters/
package com.stratum.adapters;

import android.util.Log;
import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_media_MediaPlayer_OnBufferingUpdateListener implements android.media.MediaPlayer.OnBufferingUpdateListener {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_media_MediaPlayer_OnBufferingUpdateListener(String key) {
        this.key_ = key;
        //Log.d(TAG, "[Adapter_android_media_MediaPlayer_OnBufferingUpdateListener] created key=" + key);
    }

    @Override
    public void onBufferingUpdate(android.media.MediaPlayer arg0, int arg1) {
        //Log.d(TAG, "[Adapter_android_media_MediaPlayer_OnBufferingUpdateListener] onBufferingUpdate key=" + key_ + " params=2");
        StratumInvocationHandler.nativeDispatch(
            key_, "onBufferingUpdate", new Object[]{ arg0, Integer.valueOf(arg1) });
    }

    @Override
    public String toString() {
        return "Adapter_android_media_MediaPlayer_OnBufferingUpdateListener[key=" + key_ + "]";
    }

}
